name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装gtk-3
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: 安装npm依赖
        run: npm i

      - name: 构建
        run: npm run tauri build
